version: '3'
services:
    wysiwym_eureka:
        image: vykthor/wysiwym_eureka
        ports: 
            - 9102:9102
        network_mode: host
        
    wysiwym_config_server:
        depends_on:
            - wysiwym_eureka
        image: vykthor/wysiwym_config_server
        ports: 
            - 9101:9101
        network_mode: host
        
    wysiwym_api:
        depends_on:
            - wysiwym_config_server
        image: vykthor/wysiwym_api
        ports: 
            - 8081:8081
        network_mode: host
        
    wysiwym_lds_service:
        depends_on:
            - wysiwym_api
        image: vykthor/wysiwym_lds_service
        ports: 
            - 9001:9001
        network_mode: host
        
    wysiwym_measures_service:
        depends_on:
            - wysiwym_api
        image: vykthor/wysiwym_measures_service
        ports: 
            - 9002:9002
        network_mode: host
        
    n8n_custom:
        depends_on:
            - wysiwym_lds_service
            - wysiwym_measures_service          
        image: n8n-custom
        ports:
            - 5678:5678
        network_mode: host

